## Introduction to OOP in Python
 One of the popular approach to solve a programming problem by creating objects.
 This is known as Object Oriented Programming.
 An object has two characteristics:
 1.attributes(name,age,color)
 2.behaviour(learn,study,etc)

 In Python, the concept OOP follow these things:
 1.Inheritence
 2.Encapsulation
 3.Polymorphism

 Class: A class is blueprint for the object.



## class className:
    some functions and variable
    function --- used to
    variable --- data (memory)

In [6]:
def test():
    print('test() for function')
    return
test()

test() for function


In [5]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [9]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        return
p1=Demo1()
p1.fact(5)

120

In [13]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [15]:
class Person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
    
    
    
    
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

Anil False
Akhil True


In [16]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [17]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int32


In [18]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [20]:
lst=[1,0,2,5,3,6,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(7,)
int32


In [21]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a1=np.array([1,2,3]) 
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [30]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [31]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [33]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [2]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [4]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row ",a1[0])

first row  [1 2 3]


In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row ",a1[1])

second row  [4 5 6]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row ",a1[:1])

slicing row  [[1 2 3]]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column ",a1[:,2])

slicing last column  [3 6]


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column ",a1[1:,1])

row and column  [5]


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing  column ",a1[:,1])

slicing last column  [2 5]


In [12]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value ",np.min(a1))
print("Max value ",np.max(a1))
print("Mean value ",np.mean(a1))
print("Median value ",np.median(a1))

[3.66026278 3.5394058  3.99226692 5.66310877 5.06687393 6.80332873
 5.2060392  5.07722429 5.31917177 4.21962317]
Min value  3.539405798375543
Max value  6.803328733859831
Mean value  4.85473053620896
Median value  5.072049109630605


In [13]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [14]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [15]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [6]:


import pandas as pd
dict={"name":["anil","akhil","dinesh","harsha","ajay","kranth"],"emailid":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"mobile":[999,222,456,485,258,265]}
b=pd.DataFrame(dict)
print(b)


     name           emailid  mobile
0    anil    anil@gmail.com     999
1   akhil   akhil@gmail.com     222
2  dinesh  dinesh@gmail.com     456
3  harsha  harsha@gmail.com     485
4    ajay    ajay@gmail.com     258
5  kranth  kranth@gmail.com     265


In [8]:
import calendar
c1=calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [9]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)

0 4 1 1 1 1 1 0 0 0 

In [10]:



def check(s1, s2): 
      
    # the sorted strings are checked  
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2)


The strings are anagrams.
